apache/rocketmq-externals

rocketmq-mysql/LICENSE-BIN, rocketmq-mysql/pom.xml, rocketmq-mysql/src/main/assembly/scripts/start.sh, rocketmq-mysql/src/main/assembly/scripts/stop.sh, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/Config.java, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/Replicator.java, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/binlog/EventProcessor.java, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/ha/MasterElectionLatch.java, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/position/BinlogPositionLogThread.java, rocketmq-mysql/src/main/java/org/apache/rocketmq/mysql/position/BinlogPositionManager.java, rocketmq-mysql/src/main/resources/rocketmq_mysql.conf
Add high-availability support for rocketmq-mysql-replicator in order to ensure availability, if a replicator instance crashes, another instance will be started.
JIRA:https://issues.apache.org/jira/browse/ROCKETMQ-293
* Add HA-mode for rocketmq-mysql-replicator.
* Start a zookeeper instance.
* Add the “zkAddr” property in the “rocketmq-mysql.conf” file.
* Start the replicator to verify.
https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the
change (usually before you start working on it). Trivial changes like typos
do not require a JIRA issue. Your pull request should address just this
issue, without pulling in other changes - one PR resolves one issue.
UnknownException when host config not …
=> [ROCKETMQ-293] Add high-availability support for rocketmq-mysql-replicator

rocketmq-redis/README.md, rocketmq-redis/pom.xml, rocketmq-redis/src/main/java/org/apache/rocketmq/redis/replicator/RocketMQRedisReplicator.java, rocketmq-redis/src/main/java/org/apache/rocketmq/redis/replicator/conf/ReplicatorConstants.java, rocketmq-redis/src/main/java/org/apache/rocketmq/redis/replicator/producer/RocketMQProducer.java, rocketmq-redis/src/main/resources/replicator.conf, rocketmq-redis/src/test/java/org/apache/rocketmq/redis/replicator/RocketMQRedisReplicatorTest.java
1. Add more event to downstream to rocketmq .eg(PreFullSync and PostFullSync event, AuxField event)
2. Remove global and partial config from replicator.conf.
=> Add more redis event to downstream to rocketmq.

rocketmq-spark/src/main/scala/org/apache/rocketmq/spark/streaming/MQPullInputDStream.scala
apprantly it seems a bug that the intended offsets are not stored in the timer
=> bugfix: fixup wrong offset storing in interval timer

README.md
Issue: https://github.com/apache/rocketmq-externals/issues/53
This is a minor change. Since we have merged the RocketMQ-Flink module into master, we'd better to update the home README.MD to add Rocketmq-Flink.
* update README.MD
Just document. No tests provided.
=> ISSUE-53: Added rocketmq-flink to readme

rocketmq-sentinel-sample/LICENSE, rocketmq-sentinel-sample/README.md, rocketmq-sentinel-sample/pom.xml, rocketmq-sentinel-sample/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/Constants.java, rocketmq-sentinel-sample/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/PullConsumerDemo.java, rocketmq-sentinel-sample/src/main/java/com/alibaba/csp/sentinel/demo/rocketmq/SyncProducer.java
This PR adds Sentinel samples for Apache RocketMQ. Closes #82
This PR only adds samples.
=> [ISSUE #82] Add Sentinel samples for Apache RocketMQ

rocketmq-redis/README.md, rocketmq-redis/pom.xml
Fix redis-replicator-3.0.0-RC3 expire bug.  
upgrade rocketmq-client to 4.2.0  
upgrade redis-replicator to 3.0.0-RC3  
tested in redis-replicator-3.0.0-RC3  
=> [ISSUE #91]Fix rocketmq-redis expire bug

rocketmq-console/src/main/resources/static/view/pages/cluster.html
Fix #76 
Add a ng-change for selectCluster in cluster.html
=> [ISSUE #76]Fix the problem of switch for cluster doesn't work

rocketmq-spring-boot-starter/src/main/java/org/apache/rocketmq/spring/starter/core/DefaultRocketMQListenerContainer.java
enhancement of judgment for message type in method getMessageType of DefaultRocketMQListenerContainer class [ISSUE #118 ]
XX
XXXX
=> [ISSUE #118]enhancement of judgment for message type

rocketmq-cpp/CMakeLists.txt, rocketmq-cpp/include/CCommon.h, rocketmq-cpp/include/CMessage.h, rocketmq-cpp/include/CMessageExt.h, rocketmq-cpp/include/CMessageQueue.h, rocketmq-cpp/include/CProducer.h, rocketmq-cpp/include/CPullConsumer.h, rocketmq-cpp/include/CPullResult.h, rocketmq-cpp/include/CPushConsumer.h, rocketmq-cpp/include/CSendResult.h, rocketmq-cpp/project/CMakeLists.txt, rocketmq-cpp/src/extern/CMessage.cpp, rocketmq-cpp/src/extern/CMessageExt.cpp, rocketmq-cpp/src/extern/CProducer.cpp, rocketmq-cpp/src/extern/CPullConsumer.cpp, rocketmq-cpp/src/extern/CPushConsumer.cpp, rocketmq-cpp/src/extern/CSendResult.cpp
In order to connect RocketMQ, a c-style client is needed.
Add C style APIs.
At present, this C style APIs supports
sending message in synchronous mode
consuming message using push model
=> [FEATURE REQUEST #488]Export C-style APIs for RocketMQ client

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
rockemq-flink: RocketMQSource will throw a NullPointerException
run a flink application with checkpoint
RocketMQSource will throw a NullPointerException when rocketmq do rebalance or restart flink's task .
this pr will fix the problem. [issues #152 ](https://github.com/apache/rocketmq-externals/issues/152)
XX
XXXX
=> fix rockemq-flink RocketMQSource's NPE bug

rocketmq-spring-boot-starter/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
[ISSUE-167] Send delay message in RocketMQTemplate directly
Add a new parameter to set delayLevel
XXXX
=> [ISSUE-167] Send delay message in RocketMQTemplate directly

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
batch operation should always be controlled by dimension of time and size. If no size controller, batch size might exceed the max message size, and it's hard to implement through controlling the batch time only.
add a batch size param to controll max size of messages, otherwise batch size might exceed the max message size. 
=> Add batch size param for flink sink

rocketmq-client-donet/Properties/AssemblyInfo.cs, rocketmq-client-donet/example/consumer.cs, rocketmq-client-donet/example/producer.cs, rocketmq-client-donet/rocketmq-client-donet.csproj, rocketmq-client-donet/src/ConstValues.cs, rocketmq-client-donet/src/MessageWrap.cs, rocketmq-client-donet/src/ProducerWrap.cs, rocketmq-client-donet/src/PushConsumerWrap.cs
Realize a RocketMQ donet client base on cpp client.
1 realize the donet client 
2 add the sample of producer and consumer
=> Add module rocketmq-client-donet

rocketmq-client-php/LICENSE, rocketmq-client-php/README.md, rocketmq-client-php/autocomplete/MessageQueue.php, rocketmq-client-php/src/pull_consumer.cc
fixed php client bug.
1. MessageQueue method changed.
2. fixed consumer example in README.d
3. add license.
- [] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
=> php client bug fixed.

rocketmq-prometheus-exporter/.gitignore, rocketmq-prometheus-exporter/LICENSE, rocketmq-prometheus-exporter/README.md, rocketmq-prometheus-exporter/example.rules, rocketmq-prometheus-exporter/pom.xml, rocketmq-prometheus-exporter/src/main/docker/Dockerfile, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/RocketMQExporterApplication.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/aspect/admin/MQAdminAspect.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/aspect/admin/annotation/MultiMQAdminCmdMethod.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/config/RMQConfigure.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/controller/RMQMetricsController.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/exception/ServiceException.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/BrokerMetric.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerMetric.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerQueueMetric.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ProducerMetric.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/service/AbstractCommonService.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/service/RMQMetricsService.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminInstance.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/service/impl/RMQMetricsServiceImpl.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java, rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/util/JsonUtil.java, rocketmq-prometheus-exporter/src/main/resources/application.properties, rocketmq-prometheus-exporter/src/main/resources/logback.xml, rocketmq-prometheus-exporter/style/copyright/Apache.xml, rocketmq-prometheus-exporter/style/copyright/profiles_settings.xml, rocketmq-prometheus-exporter/style/rmq_checkstyle.xml, rocketmq-prometheus-exporter/style/rmq_codeStyle.xml
RocketMQ exporter for Prometheus
exposed  RocketMQ  metrics
please  readme.md
=> RocketMQ Exporter

rocketmq-connector/pom.xml
Add An Empty RocketMQ Connector Module to externals repo.
Add An Empty RocketMQ Connector Module to externals repo.
I have already verified in my local machine.
=> [issues #242]Add An Empty RocketMQ Connector Module to externals repo.

rocketmq-console/pom.xml
It is recommended to modify the version number of RocketMQ in the Pom file.
This PR modified the version number of RocketMQ.
=> update rocketmq version

rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
Fixes #268
in the same topic, `rocketmq_consumer_offset` was accumulated one by one.
clear the `consumeOffsetMap` before collect another consumer group offset in the same topic.
Fix UnknownException when host config not exist
`. Each commit in the pull request should have a meaningful subject line and body.
=> [ISSUE #268][rocketmq-prometheus-exporter]: rocketmq_consumer_offset get a cumulative count in the same topic

rocketmq-console/src/main/resources/application.properties, rocketmq-console/src/main/resources/static/src/consumer.js, rocketmq-console/src/main/resources/static/src/i18n/en.js, rocketmq-console/src/main/resources/static/src/i18n/zh.js, rocketmq-console/src/main/resources/static/src/topic.js, rocketmq-console/src/main/resources/static/view/pages/topic.html
Fixed for Console ISSUE #260  and #261
=> Fixed Console ISSUE #260 and #261

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/TopicServiceImpl.java, rocketmq-console/src/main/resources/static/src/i18n/en.js, rocketmq-console/src/main/resources/static/src/i18n/zh.js, rocketmq-console/src/main/resources/static/src/topic.js, rocketmq-console/src/main/resources/static/view/pages/topic.html
=> ISSUE #271 Separate System Topics from Normal topic list

rocketmq-console/src/main/resources/static/src/consumer.js, rocketmq-console/src/main/resources/static/style/preLoading/main.css, rocketmq-console/src/main/resources/static/view/pages/consumer.html
=> Fix ISSUE# 256 Add loading icon for slow querying

rocketmq-flume/rocketmq-flume-sink/src/main/java/org/apache/rocketmq/flume/ng/sink/RocketMQSink.java
if any of the depending jar's are missing, an NoClassDefFoundError will be throw in the event of processing. catch throwable instead of exception.
catch throwable instead of exception in case of NoClassDefFoundError
catch throwable instead of exception
if any of the depending jar's are missing, an NoClassDefFoundError will be throw in the event of processing. catch throwable instead of exception.
=> catch throwable instead of exception in case of NoClassDefFoundError

rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/TopicController.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/TopicService.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/TopicServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/support/GlobalExceptionHandler.java, rocketmq-console/src/main/resources/static/src/message.js, rocketmq-console/src/main/resources/static/src/messageTrace.js, rocketmq-console/src/main/resources/static/src/producer.js, rocketmq-console/src/main/resources/static/view/pages/consumer.html, rocketmq-console/src/test/java/org/apache/rocketmq/console/service/impl/TopicServiceImplTest.java
As titled, fixed #254 #252 #251
=> Fixed console ISSUE for better user experience and input validation 

rocketmq-console/README.md, rocketmq-console/src/main/docker/Dockerfile
Fixed for #283 Wrong target version in README and Dockerfile
=> Fixed for #283 Wrong target version in README and Dockerfile

rocketmq-prometheus-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
… stats, just ignore this consumer
fix the bug of getting the wrong consumer offset if exception happens
if exception happens, catch the exception and ignore this consumer.
=> [rocketmq-prometheus-exporter] Avoid crash when get consumer offsets as a group of topic consuming

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
RocketMQSource contains a offsetTable to maintain queue offset.
Assume we have 15 queues in total and the flink job source has 3 parallelism.
When the job start, the first parallelism started and the other 2 has not been started yet. Then the first RocketMQSource get 15 queues. So the offsetTable has 15 entries.
When the second and third parallelism stated, then every parallelism will be assigned with 5 queues. The first parallelism still has a offsetTable with 15 entries and the other 10 entries will not be updated anymore, but all 15 queues are still snapshoted.
So when the source restart, some souce may read the wrong offset.
=> Fix the wrong offset bug when the source restart

rocketmq-connect-activemq/README-CN.md, rocketmq-connect-activemq/README.md
Readme.md is more standard
see https://github.com/apache/rocketmq-externals/tree/master/rocketmq-connect-activemq
see https://github.com/apache/rocketmq-externals/tree/master/rocketmq-connect-activemq
=> Change README.md

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
[ISSUE #229] rocketmq consumer should update offset after when flink checkpoint compeleted.
1. verify flink checkpoint is enable or not
2. RocketMQSource implement CheckpointListener
3. update offset after when flink checkpoint compeleted
=> update consumer offset after checkpoint completed

rocketmq-replicator/.gitignore, rocketmq-replicator/pom.xml, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqConstants.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceConnector.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/common/Utils.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/ConfigDefine.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/ConfigUtil.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/DataType.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/TaskConfig.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/schema/FieldName.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideStrategyEnum.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideTaskByQueue.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideTaskByTopic.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/TaskDivideStrategy.java
Define and Implement the RmqConnector and RmqSourceTask
=> Define and Implement the RmqConnector and RmqSourceTask

rocketmq-connect-runtime/README.md
Write Chinese readme
Brief changelog
Brief changelog
Issue #316
=> Write rocketmq-connect-runtime Chinese readme.md

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerConnector.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementService.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/DefaultConnectorContext.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerConnectorTest.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestConnector.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestTask.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/rest/RestHandlerTest.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImplTest.java
https://github.com/apache/rocketmq-externals/issues/323
When replica set changes, connector can actively triggers task reconfiguration
Add connectorContext support
=> [ISSUE #323] Add connectorContext support

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/converter/JsonConverter.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java, rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/FilePathConfigUtil.java, rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java
https://github.com/apache/rocketmq-externals/issues/327
Support for the latest openmessage-connector API
1、Support for the latest openmessage-connector API
2、Improving WorkSinkTask Implementation
3、Fix bug
=> [ISSUE #327]  Support for the latest openmessage-connector API

rocketmq-connect-kafka/README.md
Update README.md for rocketmq-connect-kafka
README.md
success
=> Update README.md for rocketmq-connect-kafka

rocketmq-connect/rocketmq-connect-runtime/pom.xml
=> [ISSUE #344] Update the fastjson version of runtime to 1.2.58

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
https://github.com/apache/rocketmq-externals/issues/361
Change the name of the parameter workerSourceTasks to workerTasks
XX
XXXX
=> [ISSUE #361] Change the name of the parameter workerSourceTasks to workerTasks

rocketmq-connect/README.md, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/RuntimeConfigDefine.java
#357
Supplementary readme documentation
Supplementary readme documentation
=> [ISSUE #357] Supplementary readme documentation

rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceConnector.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/common/Utils.java
on replicator. issue #351 
XXXXX
XX
XXXX
=> [ISSUE #351] rmq client setInstanceName on sourceTask

rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/TaskConfigEnum.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideTaskByTopic.java
Work for [issue](https://github.com/apache/rocketmq-externals/pull/367)
return taskConfig missing source-record-converter
XX
XXXX
=> [rocketmq-replicator]return taskConfig with source-record-converter

rocketmq-connect/rocketmq-connect-runtime/src/main/resources/logback.xml, rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSinkTask.java, rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSourceTask.java, rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/LoggerName.java
https://github.com/apache/rocketmq-externals/issues/363
File connector configures a separate log file
File connector configures a separate log file
=> [ISSUE #363] File connector configures a separate log file

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/datasync/BrokerBasedLog.java
=> [ISSUE #345]merge rmq client

rocketmq-flink/pom.xml, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQConfig.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
Add acl feature support for rocketmq-flink
XX
XXXX
=> [ISSUE #385]Add acl feature support for rocketmq-flink

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
No need to call this function twice
```String tag = topicSelector.getTag(input) != null ? topicSelector.getTag(input) : "";```
XX
success
=> No need to call this function twice

rocketmq-connect-jdbc/pom.xml, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/Config.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceConnector.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceTask.java, rocketmq-connect-jdbc/src/test/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceConnectorTest.java
Add Jdbc Source Connector and Do Unit Test
1. create pom.xml, Config.java, JdbcSourceConnector.java, JdbcSourceConnectorTest.java
I have done the unit test for JdbcSourceConnector.
=> [ISSUE #332]Add Jdbc Source Connector and Do Unit Test

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java
Automatically create target topic if target topic not exist on target cluster
1. check target topic whether exist on target cluster
2. create target topic on target cluster if missing
3. filter mq task if mq is not on src cluster
XXXX
=> [ISSUE #396]Automatically create target topic

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskTopicInfo.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java, rocketmq-replicator/src/test/java/org/apache/rocketmq/replicator/RmqSourceReplicatorTest.java
=> [ISSUE #399]Topic rename.

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskTopicInfo.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java
=> [ISSUE #397] Add DivideTaskByQueue

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
Fix sourceTaskTopicList is null
=> [ISSUE #386] Fix sourceTaskTopicList is null

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
Restful add eliminate, stopAll interface.
=> [ISSUE #379] Restful add eliminate, stopAll interface. 

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
Increase topic change awareness monitoring
=>  [ISSUE #398]Increase topic change awareness monitoring 

rocketmq-connect-kafka/README.md, rocketmq-connect-kafka/pom.xml, rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/config/ConfigDefine.java, rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/config/ConfigUtil.java, rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceConnector.java, rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTask.java, rocketmq-connect-kafka/src/main/resources/connect-kafka-source.properties, rocketmq-connect-kafka/src/test/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceConnectorTest.java
=> [ISSUE #420]remove openmessage-runtime dependency

rocketmq-connect/rocketmq-connect-runtime/pom.xml, rocketmq-replicator/pom.xml
chore(runtime/replicator): change rocketmq dependency from 4.4.0 to 4.5.2
1. change rocketmq dependency from 4.4.0 to 4.5.2
2. fix replicator can't load class
3. fix replicator can't start
Closes #431
[ISSUSE #431 ]
XXXXX
XX
XXXX
=> chore(runtime/replicator): change rocketmq dependency from 4.4.0 to 4.5.2

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
support dynamic add connector
XX
XXXX
=> [ISSUE #376] Runtime support dynamic add connector

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
rewrite 'stopAll' interface
1.  JavaLin  add 'stopAll' REST at first
2. rewrite 'stopAll' function
[ISSUSE #435]
=> [ISSUSE #435] Fix Can't access 'stopAll'

rocketmq-replicator/README.md, rocketmq-replicator/pom.xml, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/MetaSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqConstants.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/DataType.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/RmqConnectorConfig.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskConfig.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskConfigEnum.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskDivideConfig.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/offset/OffsetSync.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/offset/OffsetSyncStore.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/schema/FieldName.java, rocketmq-replicator/src/test/java/org/apache/rocketmq/replicator/RmqSourceReplicatorTest.java
sync src cluster consumer groups offset to message store
- Add MetaSourceConnector as sourceConnector for task assign
- Add MetaSourceTask as SourceTask for offset read and message sink
- Add RmqConnectorConfig for config info 
Closes #427
=> [ISSUE #427]feat(replicator):add consumer offset sync

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/RuntimeConfigDefine.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/strategy/AllocateConnAndTaskStrategyByConsistentHash.java, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/strategy/AllocateConnAndTaskStrategyByConsistentHashTest.java
- add consistentHash allocate strategy
Closes #440
=> feat(connector):Avoid of serious rebalance because of worker failed.

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/Plugin.java
=> [ISSUE #431] Fix loadclass failed from classpath

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/strategy/DefaultAllocateConnAndTaskStrategy.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java
- new configuration param: allocTaskStrategy for ConnectConfig
- use classloader load AllocateConnAndTaskStrategy impl
Closes #456
=> feat(connector): Support AllocateConnAndTaskStrategy configuration.

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
- Add syncSubConfig method on RmqMetaReplicator
Closes #438
=> feat(replicator): Support subcriptionConfig sync

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
Replicator support RocketMQConverter
https://github.com/apache/rocketmq-externals/issues/434
Replicator support RocketMQConverter
=> [ISSUES #434] Replicator support RocketMQConverter

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
- Add assign by consistentHash pattern
Closes #439
=> feat(replicator): support DivideTaskByConsistentHash

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceService.java
=> [ISSUE #465] Add friendly reminder for the lack of cluster store topic

rocketmq-connect/pom.xml, rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSourceTask.java, rocketmq-replicator/pom.xml
- Add CommitRecord call after producer send success.
Closes #450
=> feat(replicator): Add commitRecord after producer send success

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskTopicInfo.java
https://github.com/apache/rocketmq-externals/issues/470
The topic name in the TaskTopicInfo constructor should be topic
=> [ISSUE #470] The topic name in the TaskTopicInfo constructor should be topic

README.md, docs/cn/README.md
add rocketmq Chinese docs
1. update README.md
2. create 'docs' folder and 'cn' folder
3. create an new README.md in 'cn'
=> docs(docs): add rocketmq Chinese docs

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
https://github.com/apache/rocketmq-externals/issues/476
The runtime should support receive nested json
=> [ISSUE #476] The runtime should support receive nested json

rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/sink/Updater.java
Jdbc Sink Connector support repeat consumption
XX
XXXX
=> [ISSUE #485] Support repeat consumption

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-replicator/pom.xml, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
https://github.com/apache/rocketmq-externals/issues/478
TopicList is null exception and frequent requestTaskReconfiguration
=> [ISSUE #478] TopicList is null exception and frequent requestTaskReconfiguration

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-replicator/pom.xml, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/MetaSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
https://github.com/apache/rocketmq-externals/issues/492
Optimize metadata synchronization and fix RocketMQConverter bug
=> [ISSUE #492] Optimize metadata synchronization and fix RocketMQConverter bug

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-replicator/pom.xml, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/MetaSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java, rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
https://github.com/apache/rocketmq-externals/issues/503
1.Metadata synchronization bug fix
2.consumerGroup filters out the ones used in runtime
3.Multiple task consumerGroup name duplication issues
4.Incorrect offsetSyncTopic assignment in task configuration
XXXX
=> [ISSUE 503] Metadata synchronization optimization

rocketmq-connect-jdbc/README.md
update rocketmq-jdbc-connector README.md
XX
XXXX
=> [ISSUE #498] update rocketmq-jdbc-connector README.md

rocketmq-replicator/README.md
https://github.com/apache/rocketmq-externals/issues/505
Supplemental replicator documentation
XXXX
=> [ISSUE #505] Supplemental replicator documentation

rocketmq-replicator/README.md
1. rewrite replicator README.md
Close: #505
XXXXX
XX
XXXX
=> [ISSUE #505]docs(replicator): add introduction of replicator

rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/Config.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/DataType.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/DbConnectorConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/SinkDbConnectorConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/SourceDbConnectorConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/TaskDivideConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/TaskTopicInfo.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSinkConnector.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSinkTask.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceConnector.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceTask.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideStrategyEnum.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideTaskByConsistentHash.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideTaskByQueue.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideTaskByTopic.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/TaskDivideStrategy.java
=> [ISSUE #489] JDBC Connector support divide task by topic strategy

rocketmq-connect-redis/pom.xml, rocketmq-connect-redis/src/main/java/org/apache/rocketmq/connect/redis/common/Options.java, rocketmq-connect-redis/src/main/java/org/apache/rocketmq/connect/redis/common/RedisConstants.java, rocketmq-connect-redis/src/main/java/org/apache/rocketmq/connect/redis/parser/SetParser.java, rocketmq-redis/pom.xml
rocketmq-connect-redis and rocketmq-redis redis 6 support
redis 6 set command add an option KEEPTTL
support redis 6 ACL
support redis 6 SSL
XXXX
=> rocketmq-connect-redis and rocketmq-redis redis 6 support

rocketmq-console/src/main/java/org/apache/rocketmq/console/App.java
Remove unnecessary annotations
Remove unnecessary annotations (@EnableAutoConfiguration)
#518
=> Remove unnecessary annotations

rocketmq-knative/source/config/500-controller.yaml, rocketmq-knative/source/sample/apacherocketmqsource.yaml, rocketmq-knative/source/sample/event-display.yaml
Add rocketmqsource sample and update source images
1 Add  sample
2 Update docker images of controller and adapter
=> Add rocketmqsource sample

rocketmq-connect-jdbc/pom.xml
Replace openmessaging-connector:0.1.1-beta-SNAPSHOT with openmessaging-connector:0.1.0-beta in pom.xml
XXXXX
XX
XXXX
=> [ISSUE #526] Cannot resolve io.openmessaging:openmessaging-connector:0.1.1-beta-SNAPSHOT

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java, rocketmq-flink/style/rmq_checkstyle.xml
#532 
Fix the build failure due to Checkstyle issues in rocketmq-flink and update the checkstyle file as of the parent file located at  [apache/rocketmq/style/rmq_checkstyle.xml](https://github.com/apache/rocketmq/blob/master/style/rmq_checkstyle.xml)
1. Update Checkstyle file
2. Fix RocketMQSource Checkstyle issue in line 334
=> [ISSUE #532] Fix Checkstyle issue in rocketmq-flink

rocketmq-connect/pom.xml, rocketmq-connect/rocketmq-connect-runtime/pom.xml, rocketmq-connect/rocketmq-connect-runtime/run_worker.sh, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestTask.java, rocketmq-connect/rocketmq-connect-sample/pom.xml
#541 
Fix the `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` failure 
1. Add Apache copyright in  rocketmq-connect/rocketmq-connect-runtime/pom.xml
2. Add Apache copyright in  rocketmq-connect/rocketmq-connect-runtime/run_worker.sh
3. Add Apache copyright in  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestTask.java
4. Add Apache copyright in  modified:   rocketmq-connect/rocketmq-connect-sample/pom.xml
5. Add XML head in rocketmq-connect/pom.xml
=> [ISSUE #541] Fix Checkstyle issue in rocketmq-connect

rocketmq-connect-jdbc/pom.xml, rocketmq-connect/rocketmq-connect-runtime/pom.xml
2.add rocketmq-tools dependency so rocketmq-connect-jdbc can run on it
Add rocketmq-tools dependency in rocketmq-connect-runtime 
so the rocketmq-connect-jdbc can run on it.
2.add rocketmq-tools dependency so rocketmq-connect-jdbc can run on it
1. `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle`  failed with message
```
Rat check: Summary over all files. Unapproved: 3, unknown: 3, generated: 0, approved: 76 licenses
```
It's probably 3 files  didn't have the specification, will figure this out in another issue.
2. `mvn clean install -DskipITs` succeeded
3. `mvn clean test-compile failsafe:integration-test` succeeded
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 …
=> [ISSUE #536]add rocketmq-tools dependency in connect runtime

rocketmq-connect-jdbc/README.md, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/Config.java
Add 2 required field in jdbc sink connector configuration
1. add `source-rocketmq` and `source-cluster` to required config entries like :
```
public static final Set<String> REQUEST_CONFIG = new HashSet<String>() {
{
add(CONN_DB_IP);
add(CONN_DB_PORT);
add(CONN_DB_USERNAME);
add(CONN_DB_PASSWORD);
add(CONN_DB_MODE);
add("rocketmqTopic");
add(CONN_SOURCE_RMQ);
add(CONN_SOURCE_CLUSTER);
}
};
```
and in docs
=> [ISSUE #538] WIP: Add required field in jdbc connector in code and documentation

rocketmq-connect-jdbc/pom.xml, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/common/CloneUtils.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/common/ConstDefine.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/common/DBUtils.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/Config.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/SinkDbConnectorConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/SourceDbConnectorConfig.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSinkConnector.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceTask.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/sink/Updater.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/source/Querier.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/source/TimestampIncrementingQuerier.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideTaskByQueue.java, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/strategy/DivideTaskByTopic.java
fix jdbc-connector bug
XX
XXXX
=> [ISSUE #545]bug fix

rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/config/Config.java
#550 
Remove unnecessary value of REQUEST_CONFIG member variable in config class
Deleve `add("rocketmqTopic");` in Config.java of rocketmq-connect-jdbc
XXXX
=> [ISSUE #550] (jdbc-connector) Removed unnecessary value of REQUEST_CONFIG in Config.java

rocketmq-connect-redis/pom.xml
update rocketmq-connect-redis dependency
```
<dependency>
<groupId>io.openmessaging</groupId>
<artifactId>openmessaging-connect</artifactId>
<version>0.1.1</version>
</dependency>
```
change to
```
<dependency>
<groupId>io.openmessaging</groupId>
<artifactId>openmessaging-connector</artifactId>
<version>0.1.1</version>
</dependency>
```
```
<dependency>
<groupId>io.openmessaging</groupId>
<artifactId>openmessaging-connect</artifactId>
<version>0.1.1</version>
</dependency>
```
change to
```
<dependency>
<groupId>io.openmessaging</groupId>
<artifactId>openmessaging-connector</artifactId>
<version>0.1.1</version>
</dependency>
```
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the …
=> update rocketmq-connect-redis dependency

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
fix a possible type in connect runtime WorkerSourceTask
1. changed to `Optional<ByteBuffer> oposition = Optional.ofNullable(position);`
XXXX
=> [ISSUE #564] Fix typo

rocketmq-connect-jdbc/pom.xml, rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/common/DBUtils.java
Fix Issue #554 
1. updated Druid version to avoid a known bug
2. use DruidDataSource to set 2 necessary options.
=> [ISSUE #554] Update druid version and set ConnectionErrorRetryAttempts

rocketmq-flink/pom.xml
=> feat(rocketmq-flink)upgrade rocketmq client to 4.7.1

rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSinkConnector.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
1. make sure JdbcSinkConnector listener is closed on `stop()`
=> [ISSUE #558] An ugly solution for fetch topic list error

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectStartup.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTaskState.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/TaskPositionCommitService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/store/FileBaseKeyValueStore.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/store/MemoryBasedKeyValueStore.java
1. added task level lifecycle management
2. fixed bug : stopAll cannot stop all sometimes
3. enhanced some restful api to output json format data
4. fixed some trivial bugs including typos
XX
XXXX
=> [ISSUE #540] Add task lifecycle management; fix stopAll bug

rocketmq-console/src/main/java/org/apache/rocketmq/console/App.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/task/DashboardCollectTask.java, rocketmq-console/src/main/resources/static/src/controller.js
1. use StopWatch.createUnstarted() to avoid start nano time twice
2. use  tpsArray[2] instead of tpsArray[3] to get inTPS
XX
XXXX
=> [ISSUE #591] nanotimer started twice

rocketmq-console/README.md
=> [ISSUE #531]updated rocketmq console readme t

rocketmq-console/src/main/java/org/apache/rocketmq/console/model/GroupConsumeInfo.java
Fixed bug in GroupConsumeInfo#compareTo, do not convert long to int.
Do not convert long to int.
XXXX
=> Fix bug in GroupConsumeInfo#compareTo.

rocketmq-console/src/main/java/org/apache/rocketmq/console/config/AuthWebMVCConfigurerAdapter.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/LoginServiceImpl.java, rocketmq-console/src/main/resources/application.properties
1. fix the bug described in ISSUE #614 
2. restrict access to protected resources
XX
XXXX
=> [ISSUE #614] redirect too many times after enable user login

rocketmq-console/README.md
=> [#ISSUE 625]doc(rocketmq-console) use rocketmq-console

rocketmq-console/src/main/resources/static/view/pages/login.html
Fix the bug that the password input box placeholder is set to USER_NAME
=> Fix the bug that the password input box placeholder is set to USER_NAME

rocketmq-iot-bridge/bin/server.sh, rocketmq-iot-bridge/pom.xml
issue #646 
Fix compile and start script error
XXXX
=> [ISSUE #646] Fix start script error, fix slf4j binder error

rocketmq-console/src/main/resources/static/view/pages/ops.html
fix the [issue#641](https://github.com/apache/rocketmq-externals/issues/641)
=> [ISSUE #641]Rename NameSrvAddrList to NameServerAddressList in OPS Page

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
1. when a queue is paused, we do not pull message from that queue.
XX
XXXX
=> [ISSUE #612]bug(connect-runtime) stop polling from paused tasks

rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/MQTTBridge.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/example/MqttSampleConsumer.java, rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/integration/ConsumeMessageIntegrationTest.java
ISSUE #660 
1.remove useless import and duplicate code
2.start netty server with port
XXXX
=> [ISSUE #660] Remove useless code, start server only use port

rocketmq-console/src/main/java/org/apache/rocketmq/console/task/DashboardCollectTask.java
issue #610 
metrcis not exitst in BrokerStatsManager will return response with "The stats <%s> <%s> not exist"
the topic is exist, only the key not exists in stats manager, IMO some simple warn log is enough, error log will cause confusion.
XXXX
=> [ISSUE #610] Fix metrics not exists print so much error log

rocketmq-console/src/main/java/org/apache/rocketmq/console/task/DashboardCollectTask.java
Filter system topic while console dashboard was making topic statistics.
=> [ISSUE #665] Filter system topic while console dashboard was making topic statistics

rocketmq-console/src/main/java/org/apache/rocketmq/console/task/DashboardCollectTask.java
mvn clean package -Dmaven.test.skip=true
[INFO] Starting audit...
java\org\apache\rocketmq\console\task\DashboardCollectTask.java:330:12: error: 'for' is not followed by whitespace.
java\org\apache\rocketmq\console\task\DashboardCollectTask.java:330:76: error: '{' is not preceded with whitespace.
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
XXXXX
XX
XXXX
=> [ISSUE #670] Fix building error

rocketmq-console/pom.xml
Upgrade RocketMQ version
Upgrade RocketMQ version
XXXX
=> [ISSUE #666] Upgrade RocketMQ version

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/DashboardCollectServiceImpl.java
issue #678 
dashboard UI throw a notification every minute when set rocketmq.config.enableDashBoardCollect=false
XXXX
=> [ISSUE #678] Fix dashboard notification when set rocketmq.config.enableDashBoardCollect=false

rocketmq-connect-jdbc/README.md
The config infomation has been verified. This update could be a draft version config template in README.md and some parts of it will probobaly be changed in the close future.
Update config template in README.md
1. Update config template for starting/creating jdbc connectors
2. Add config example
3. Update config table
=> [ISSUE #552] (jdbc-connector) Update README.md

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/ConsumerServiceImpl.java
issue #680 
do not print too much log with stack info
XXXX
=> [ISSUE #680] Fix too much warn log because non-exist retry topic

rocketmq-console/src/main/resources/static/src/message.js, rocketmq-console/src/main/resources/static/view/pages/message.html
issue #652 
Support DLQ topic resend message
XXXX
=> [ISSUE #652]Support DLQ topic resend message

rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java, rocketmq-console/src/main/resources/static/view/pages/messageTrace.html, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtilTest.java
issue #682 
1. add client host field
2. add compatbile logic when decode trace msg
XXXX
=> [ISSUE #682] Fix wrong message trace detail 

rocketmq-console/pom.xml, rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/MessageController.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessagePage.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessagePageTask.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageQueryByPage.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/QueueOffsetInfo.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/request/MessageQuery.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/MessageService.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageServiceImpl.java, rocketmq-console/src/main/resources/static/src/message.js, rocketmq-console/src/main/resources/static/view/pages/message.html
#654 Support query more than 2000 message by page
1. Find beginOffset and endOffset according to the start time and end time
2. Eliminate all offsets whose start time is incorrect
3. Eliminate all offsets whose end time is incorrect
4. Save the current query status to the local cache, and generate a taskId to send to the front end for the next query
5. The next query brings taskId to query the remaining pages based on the offset of the last query
XXXX
=> [ISSUE #654] Support query message by page

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
=> [Replicator] Fix message duplication problem

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementService.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/TaskPositionCommitService.java, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestPositionManageServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/rest/RestHandlerTest.java
issue: #693 
1. Unified cache of position information
2. Synchronize position information before worker stops
3. Unit test bug fix
XX
Source Cluster:
Target Cluster:
During the synchronization process, the stop-start operation is performed intermittently. After the synchronization task is executed, it is confirmed that the number of synchronization messages is the same.
=> [ISSUE #693][Replicator] Connector restart causes a lot of duplicate data

rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/ConsumerController.java, rocketmq-console/src/main/resources/static/src/i18n/zh.js, rocketmq-console/src/main/resources/static/src/topic.js, rocketmq-console/src/main/resources/static/view/pages/topic.html
=> [ISSUE #711] Consumers can skip the accumulation of messages.

rocketmq-console/src/main/resources/static/src/ops.js, rocketmq-console/src/main/resources/static/view/pages/ops.html
fix rocketmq console fail to update nameserver address
XX
XXXX
=> [ISSUE #720]  fix rocketmq console fail to update nameserver address

rocketmq-flink/pom.xml, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/RocketMQSource.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/common/RocketMQOptions.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/enumerator/RocketMQSourceEnumerator.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/RocketMQPartitionSplitReader.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/BytesMessage.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/DeserializationSchema.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/DirtyDataStrategy.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/RocketMQDeserializationSchema.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/RocketMQRowDeserializationSchema.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/RowDeserializationSchema.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/table/RocketMQDynamicTableSourceFactory.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/table/RocketMQScanTableSource.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/util/ByteSerializer.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/util/ByteUtils.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/util/StringSerializer.java, rocketmq-flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, rocketmq-flink/src/test/java/org/apache/rocketmq/flink/source/reader/deserializer/RocketMQRowDeserializationSchemaTest.java
At present, RocketMQ connector supports the implementation of new Source interface, which needs the `ScanTableSource` implementation to expand Table/SQL capabilities. RocketMQ connector should support the RocketMQ TableSource based on `RocketMQSource`.
- Introduce `RocketMQScanTableSource` based on the implementation of new `Source` interface.
=> [#715] Support the RocketMQ TableSource based on the new Source interface

rocketmq-console/src/main/resources/static/src/consumer.js, rocketmq-console/src/main/resources/static/src/topic.js
=> [ISSUE #723] When the operation is successful, the dialog will close automatically

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/TopicServiceImpl.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/BaseTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/BaseControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/TopicControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MyPrintingResultHandler.java
=> [ISSUE #673] Add unit tests for TopicController.

rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java
https://github.com/apache/rocketmq/issues/2996
XX
XXXX
=> [ISSUE #2996] Adjust the way to get the clientHost in the message trace

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageServiceImpl.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/MessageControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MockObjectUtil.java
=> [ISSUE #673] Add unit tests for MessageController.

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImpl.java, rocketmq-console/src/main/resources/static/src/messageTrace.js, rocketmq-console/src/main/resources/static/view/pages/messageTrace.html, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MockObjectUtil.java
Message trace data table improvement
Make message trace data easier to understand.
We will mainly have two parts of data, **Send Message Trace** and **Consume Message Trace**.
1. Send Message Trace has **message trace basic information** and **transaction message trace**.
2. Consume Message Trace has **message consume trace**, which is  group by subscription group.
All trace data are sorted in **descending** order 
=> [ISSUE #745] Message trace data table improvement

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java
#696 
Support multi-producer instances to improve write performance.
1. Add producer and consumer initialization public methods.
2. Each source task creates a producer instance.
3. Optimize the creation of too many groups when the service restarts.
XXXX
=> [ISSUE #696] Multi-producer instance.

rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/LoginController.java, rocketmq-console/src/main/resources/static/src/app.js, rocketmq-console/src/main/resources/static/src/controller.js, rocketmq-console/src/main/resources/static/src/login.js
fix issue #750 
* when trigger login/logout action, redirect to login page use server.servlet.context-path
* login/check.query use relative path
=> [ISSUE #750] rocketmq-console：It does not work when setting server.servlet.context-path in application.properties

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/ClusterServiceImpl.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/ClusterControllerTest.java
=> [ISSUE #673] Add unit tests for ClusterController.

rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/OpsControllerTest.java
=> [ISSUE #673] Add unit tests for OpsController.

rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/model/trace/MessageTraceStatusEnum.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImpl.java, rocketmq-console/src/main/resources/static/src/messageTrace.js, rocketmq-console/src/main/resources/static/view/pages/messageTrace.html
improve message trace UI
* Change Send Message Info UI
* Handle edge case: consume trace subBefore or subAfter trace is missing (if subAfter trace is missing, the status will be unknown)
* Fix timestamp typo
* Time format for ms
* Change costTime color from white to black
* Remove graph and data format button
* Fix message trace graph when producer send message cost time < 1 ms
=> [ISSUE #756] [RocketMQ-Console] Improve message trace UI

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/TaskPositionCommitService.java
one of twice-position-synchronization should change to offset-synchronization
XX
XXXX
=> [ISSUE #758]fix(connect-runtime)The PositionCommitTaskPosition has no synchronized offset

rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/NamesvrControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/ProducerControllerTest.java
=> [ISSUE #673] Add unit tests for ProducerController and NamesvrController

rocketmq-console/src/main/resources/static/vendor/ng-dialog/ngDialog-theme-default.css, rocketmq-console/src/main/resources/static/view/pages/consumer.html, rocketmq-console/src/main/resources/static/view/pages/message.html
=> [ISSUE #766] Optimize console UI

rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java, rocketmq-console/src/main/resources/static/src/messageTrace.js, rocketmq-console/src/main/resources/static/view/pages/messageTrace.html
make RocketMQ console message trace compatible with older version RocketMQ client
* if have both subBefore and subAfter trace
* <=4.7.1 and > 4.9.0 endTimestamp use beginTimestamp + costTime
* 4.9.0 use real endTimestamp
* if subBefore is missing
* all version beginTimestamp and retryTime is missing
* <=4.7.1 and > 4.9.0 will lost endTimestamp and groupName **but 4.9.0 works well**
* if subAfter is missing
* all version endTimeStamp and status is missing
**Suggest add subAfter timestamp and groupName back to provide a better use experience.**
https://github.com/apache/rocketmq/pull/3137
* handle old version client  subBefore trace missing case
* handle old version client  subAfter trace missing case
* missing value use N/A instead of --
* consume message trace use beginTime + costTime if …
=> [ISSUE #768] Console message trace compatibility

rocketmq-console/src/main/java/org/apache/rocketmq/console/aspect/admin/MQAdminAspect.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/config/RMQConfigure.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/OpsController.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/OpsService.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/client/MQAdminInstance.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/OpsServiceImpl.java, rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/TopicServiceImpl.java, rocketmq-console/src/main/resources/application.properties, rocketmq-console/src/main/resources/static/src/ops.js, rocketmq-console/src/main/resources/static/view/pages/ops.html, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/MessageControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/TopicControllerTest.java
#773 add useTLS configure for rocketmq console
XX
XXXX
=> [ISSUE #773] add useTLS configure for rocketmq console

rocketmq-console/pom.xml, rocketmq-console/src/test/java/org/apache/rocketmq/console/admin/MQAdminAspectTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/admin/MQAdminExtImplTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/config/RMQConfigureTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/ProducerControllerTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/task/DashboardCollectTaskTest.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MockObjectUtil.java, rocketmq-console/src/test/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtilTest.java
=> [ISSUE #673]Add unit tests to improve code coverage

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
#702 
First check the running task, when checking task status.
1. First check the running tasks.
2. If some tasks are closed, synchronize the position.
XXXX
=> [#702] Adjust task check order

rocketmq-flink/src/main/java/org/apache/rocketmq/flink/common/RocketMQOptions.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RocketMQSink.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/sink/table/RocketMQDynamicTableSink.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/sink/table/RocketMQDynamicTableSinkFactory.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/sink/table/RocketMQRowDataConverter.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/sink/table/RocketMQRowDataSink.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/table/RocketMQDynamicTableSourceFactory.java, rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/util/StringSerializer.java, rocketmq-flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, rocketmq-flink/src/test/java/org/apache/rocketmq/flink/sink/table/RocketMQDynamicTableSinkFactoryTest.java
At present, RocketMQ connector supports the implementation of legacy SinkFunction interface, which needs the `DynamicTableSink` implementation to expand Table/SQL capabilities. RocketMQ connector should support the RocketMQ TableSink based on the legacy SinkFunction interface.
- Introduce `RocketMQDynamicTableSink` based on the implementation `RocketMQSink` of legacy `SinkFunction` interface.
=> [#780] Support the RocketMQ TableSink based on the legacy Sink implementation

rocketmq-flink/README.md
At present, RocketMQ connector supports the table implementation of Source and Sink interface. RocketMQ SQL connector should introduce the document for the usage of table source and sink.
- Introduce the usage of RocketMQ SQL connector in the `README.md`.
=> [#715] Introduce RocketMQ SQL connector document

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
Allocate strategy only support in topic level, this pr support in topic queues level.
=> Support divide by topic queue rebalance allocate strategy

rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/MQTTBridge.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/config/MqttBridgeConfig.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/configuration/MQTTBridgeConfiguration.java
=> [ISSUE #813]make the server to support heartbeat to release invalid long connections

rocketmq-cloudevents-binding/pom.xml, rocketmq-cloudevents-binding/src/main/java/org/apache/rocketmq/cloudevent/RocketMQMessageFactory.java, rocketmq-cloudevents-binding/src/main/java/org/apache/rocketmq/cloudevent/impl/RocketMQBinaryMessageReader.java, rocketmq-cloudevents-binding/src/main/java/org/apache/rocketmq/cloudevent/impl/RocketMQHeaders.java, rocketmq-cloudevents-binding/src/main/java/org/apache/rocketmq/cloudevent/impl/RocketMQMessageWriter.java, rocketmq-cloudevents-binding/src/test/java/org/apache/rocketmq/cloudevent/RocketMQMessageWriterTest.java, rocketmq-cloudevents-binding/src/test/java/org/apache/rocketmq/cloudevent/RocketmqMessageFactoryTest.java
Implement the conversion from rocketmq message to cloudevent
1. BinaryMessage read / write
2. StructuredMessage read / write
=> [ISSUE #810]rocketmq-cloudevent-binding

rocketmq-iot-bridge/pom.xml, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/MQTTBridge.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/config/MqttBridgeConfig.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/configuration/MQTTBridgeConfiguration.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/util/HttpAPIClient.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/connection/client/ClientManager.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/connection/client/impl/ClientManagerImpl.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/constant/MqttConstant.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/MqttConnectionHandler.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttSubscribeMessageHandler.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttUnsubscribeMessagHandler.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/rest/HttpRestHandler.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/rest/HttpRestHandlerImp.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/rest/common/Connection.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/rest/common/ConnectionInfo.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/rest/common/ContextResponse.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/ConsumerPullTask.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/RocketMQPublishProducer.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/RocketMQSubscribeConsumer.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/subscription/impl/InMemorySubscriptionStore.java
#811 
Add a lite http server into this project for user to query the connected info.
This feature has been used in our company for a long time.
=> [ISSUE #811] Support to query the info of client connection

rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
#699 
When the source task starts, check whether the position has been completed synchronously.
1. Filter out configs where brokerName and queueId do not exist.
2. Obtain the position twice at intervals, and compare whether the positions obtained twice before and after are consistent.
2.1 If they are consistent, the current position is considered to be the latest
2.2 If inconsistent, re-compare until timeout.
XXXX
=> [ISSUE #699] The source task starts to check the position

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java, rocketmq-connect/rocketmq-connect-runtime/src/main/resources/log4j.properties, rocketmq-connect/style/rmq_checkstyle.xml
https://github.com/apache/rocketmq-externals/issues/817
- Format the WorkerSourceTask class
- Modify the log configuration class format header
- Modify checkstyle configuration
=> [ISSUE #817] fix checkstyle

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/datasync/BrokerBasedLog.java, rocketmq-connect/rocketmq-connect-runtime/src/main/resources/connect.conf
#821 
- Auto create subGroup
XXXX
=> [ISSUE #821] Support auto create subGroup

rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceConnector.java, rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTask.java
for issue: #853 
[rocketmq-connect-kafka]: Completion method KafkaSourceTask#pause(), KafkaSourceTask#resume().
[rocketmq-connect-kafka]: Normalized code style
=> [rocketmq-connect-kafka]: Completion method KafkaSourceTask#pause(), KafkaSourceTask#resume()

rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java, rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImplTest.java
#697 
When the local position is merged with the synchronized data, it is impossible to check whether the synchronized data is the latest data, resulting in the situation that the new position is overwritten by the previous position.
In order to solve the above problems, we require that when each worker node synchronizes its position with other nodes, it synchronizes the updated position of the local task to ensure that other worker nodes get the latest position.
1. Config management service log print modification.
2. Record the updated position of the local task.
3. Only the updated position is synchronized, when synchronizing with other nodes.
4. The synchronized position is not merged to the local to avoid overwriting the latest local position, when the new node is online.
ps: Other …
=> [#697] Synchronize the latest local position between worker nodes.

rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/example/MqttSampleConsumer.java, rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttConnectMessageHandler.java
=> Fix spelling mistakes

rocketmq-connect-redis/src/main/java/org/apache/rocketmq/connect/redis/parser/SetParser.java
=> [ISSUE #861]Fix exception parsing redis command "set a 1010 px 1000"

README.md
=> [ISSUE #871] readme add rocketmq connect repository link 

rocketmq-beats-integration/README.md, rocketmq-beats-integration/libbeat/outputs/rocketmq/LICENSE, rocketmq-beats-integration/libbeat/outputs/rocketmq/NOTICE, rocketmq-beats-integration/libbeat/outputs/rocketmq/client.go, rocketmq-beats-integration/libbeat/outputs/rocketmq/config.go, rocketmq-beats-integration/libbeat/outputs/rocketmq/rocketmq.go
#877 
First version of RocketMQ output of Beats.
XXXX
=> [ISSUE 877] Add RocketMQ output of Elastic Beats

rocketmq-rocksdb/LICENSE, rocketmq-rocksdb/NOTICE, rocketmq-rocksdb/README.md, rocketmq-rocksdb/RemoveConsumeQueueCompactionFilter.java, rocketmq-rocksdb/build-win.bat, rocketmq-rocksdb/remove_consumequeue_compactionfilter.cc, rocketmq-rocksdb/remove_consumequeue_compactionfilter.h, rocketmq-rocksdb/remove_consumequeue_compactionfilterjni.cc, rocketmq-rocksdb/thirdparty.inc
Which Issue(s) This PR Fixes
Fixes #921
Brief Description
This RIP mainly optimizes and solves the existing perfermance problems in the million-topic scenario from two levels:
1.Metadata like topic, subscription, consumerOffset implement kv storage
2.ConsumeQueue index file implements kv storage
And current proposal teaches you how to compile rocksdb in different environments and generate a dynamic link library
=> [ISSUE #921]rocksdb for rocketmq

rocketmq-rocksdb/pom.xml
fix #923 
rocketmq-rocksdb adds pom.xml
=> rocketmq-rocksdb adds pom.xml

rocketmq-rocksdb/remove_consumequeue_compactionfilter.h
=> [ISSUE #927] change cqUnit size from 36 to 28

rocketmq-rocksdb/README.md
=> [rocketmq-rocksdb]Format readme

rocketmq-serializer/rocketmq-serializer-json/pom.xml
Upgrade fastjson version
Upgrade fastjson version
XXXX
=> Upgrade fastjson version
