apache/rocketmq-externals

- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/MessageSet.java
bug in MessageSet, newly created iterator will make hasNext() always return true, which will make MessageSet spit endless data items.
> fixup endless data in MessageSet due to newly created iterator

- spring-boot-starter-rocketmq/.gitignore
- spring-boot-starter-rocketmq/.travis.yml
- spring-boot-starter-rocketmq/LICENSE
- spring-boot-starter-rocketmq/README.md
- spring-boot-starter-rocketmq/README_zh_CN.md
- spring-boot-starter-rocketmq/pom.xml
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/RocketMQAutoConfiguration.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/RocketMQProperties.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/annotation/RocketMQMessageListener.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/DefaultRocketMQListenerContainer.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/DefaultRocketMQListenerContainerConstants.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQConsumerLifecycleListener.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQListener.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQListenerContainer.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQPushConsumerLifecycleListener.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQTemplate.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/enums/ConsumeMode.java
- spring-boot-starter-rocketmq/src/main/java/org/apache/rocketmq/spring/starter/enums/SelectorType.java
- spring-boot-starter-rocketmq/src/main/resources/META-INF/spring.factories
- spring-boot-starter-rocketmq/src/test/java/org/apache/rocketmq/spring/starter/RocketMQAutoConfigurationTests.java
Provider a rocketmq-spring adapter for the convenience of the spring user.
Help developers quickly integrate [RocketMQ](http://rocketmq.apache.org/) in [Spring Boot](http://projects.spring.io/spring-boot/). Support the Spring Message specification to facilitate developers to quickly switch from other MQ to RocketMQ.
JIRA: [https://issues.apache.org/jira/browse/ROCKETMQ-120](https://issues.apache.org/jira/browse/ROCKETMQ-120)
Features:
please see: [project readme](https://github.com/aqlu/rocketmq-externals/blob/master/spring-boot-starter-rocketmq/README.md)
> [ROCKETMQ-120] Provider a adapter for spring and spring-boot

- rocketmq-jms/core/src/main/java/org/apache/rocketmq/jms/domain/message/JmsBaseMessage.java
The method is checking whether the "name" exists in the "headers" or not, thus the method should be named "exists" but not "headExits".
public boolean headerExits(String name) {	
return this.headers.containsKey(name);]
}
> Change the method name "headExits" to "exists".

- rocketmq-spark/spark-structured-streaming-rocketmq.md
This is a complement for PR #72 to fix the copy-pasted 'Kafka' words in documents.
Docs only. See commit diff for details.
> [ISSUE #71] Refine documents

- rocketmq-hbase/README.md
- rocketmq-hbase/pom.xml
- rocketmq-hbase/rocketmq-hbase-sink/README.md
- rocketmq-hbase/rocketmq-hbase-sink/pom.xml
- rocketmq-hbase/rocketmq-hbase-sink/src/main/java/org/apache/rocketmq/hbase/sink/DataRow.java
- rocketmq-hbase/rocketmq-hbase-sink/src/main/java/org/apache/rocketmq/hbase/sink/Replicator.java
- rocketmq-hbase/rocketmq-hbase-sink/src/main/java/org/apache/rocketmq/hbase/sink/RocketMQProducer.java
- rocketmq-hbase/rocketmq-hbase-sink/src/main/java/org/apache/rocketmq/hbase/sink/Transaction.java
- rocketmq-hbase/rocketmq-hbase-sink/src/test/java/org/apache/rocketmq/sink/ReplicatorTest.java
- rocketmq-hbase/rocketmq-hbase-source/LICENSE-BIN
- rocketmq-hbase/rocketmq-hbase-source/NOTICE-BIN
- rocketmq-hbase/rocketmq-hbase-source/README.md
- rocketmq-hbase/rocketmq-hbase-source/pom.xml
- rocketmq-hbase/rocketmq-hbase-source/src/main/assembly/assembly.xml
- rocketmq-hbase/rocketmq-hbase-source/src/main/assembly/scripts/start.sh
- rocketmq-hbase/rocketmq-hbase-source/src/main/assembly/scripts/stop.sh
- rocketmq-hbase/rocketmq-hbase-source/src/main/java/org/apache/rocketmq/hbase/source/Config.java
- rocketmq-hbase/rocketmq-hbase-source/src/main/java/org/apache/rocketmq/hbase/source/HBaseClient.java
- rocketmq-hbase/rocketmq-hbase-source/src/main/java/org/apache/rocketmq/hbase/source/MessageProcessor.java
- rocketmq-hbase/rocketmq-hbase-source/src/main/java/org/apache/rocketmq/hbase/source/RocketMQConsumer.java
- rocketmq-hbase/rocketmq-hbase-source/src/main/java/org/apache/rocketmq/hbase/source/RocketMQSource.java
- rocketmq-hbase/rocketmq-hbase-source/src/main/resources/logback.xml
- rocketmq-hbase/rocketmq-hbase-source/src/main/resources/rocketmq_hbase.conf
- rocketmq-hbase/rocketmq-hbase-source/src/test/java/org/apache/rocketmq/hbase/source/RocketMQSourceTest.java
- rocketmq-hbase/style/copyright/Apache.xml
- rocketmq-hbase/style/copyright/profiles_settings.xml
- rocketmq-hbase/style/rmq_checkstyle.xml
- rocketmq-hbase/style/rmq_codeStyle.xml
_The work covered by this PR was carried out as part of the GSoC 2018._
This PR provides plugins that integrate RocketMQ with the HBase database. Namely, it includes (i) the HBase sink, that replicates HBase tables to RocketMQ topics; and (ii) the HBase source, which replicates RocketMQ topics to HBase tables.
The HBase sink functions as a replication endpoint for HBase. This endpoint can track updates (put and delete operations) performed on specified tables, and replicate them to a RocketMQ topic using reliable synchronous transmission.
The HBase source consists of a daemon program that is continuously pulling messages, at regular time intervals, from specified RocketMQ topics and writing them to HBase tables using a broadcast message model.
Code is documented and unit tests are …
> [GSoC Project] RocketMQ HBase Connector

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
Fix load wrong offset from savepoint
Every time flink program starts from savepoint, rocketMQSource will load some wrong offset, and consume a lot of expired data.
> fix(module): fix load wrong offset from savepoint

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
Fix [ISSUE 306](https://github.com/apache/rocketmq-externals/issues/306)
When a job consumes messages from ClusterA and sends messages to ClusterB.  Because Flink operators may be chained, the consumer and producer is possible running in the same JVM process. The default instanceName creator creates the same instanceName for the producer and consumer, then the messages will be not sent to the ClusterB. 
Add setInstanceName method to Sink and Source, so the user could set the custom instanceName.
> [ISSUE 306][Flink] Support consume/produce from/to different cluster in the same process.

- rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTask.java
#341 
Add wakeup before kafka consumer close to wakeup consumer poll
KafkaSourceTask.java
XXXX
> [ISSUE #341] Add wakeup before kafka consumer close to wakeup consumer poll

- rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSinkTask.java
https://github.com/apache/rocketmq-externals/issues/359
Fix file connect sink task stop bug
Fix file connect sink task stop bug
>  [ISSUE #359] Fix file connect sink task stop bug

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
When rocketMQ is not stable, producer might fail to send message。In such case, 
(1) method #flushSync might throw exception, thus  method #close will be called. 
(2)The problem is method #close  will call method #flushSync again before shutdown producer, so shutdown might fail.
(3)if shutdown fail, RocketMQSink could not create producer again with the same instanceName.
add try {} catch {} block to make sure producer#shutdown will be called as expected.
> Fix bug. Producer failed to shutdown when exception happened

- rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
https://github.com/apache/rocketmq-externals/issues/469
When replicator stop, stop MQAdminExt and Listener
> [ISSUE #469] When replicator stop, stop MQAdminExt and Listener

- rocketmq-console/src/main/resources/static/src/consumer.js
Change the message when create or update consumer monitor is success to avoid misleading. 
Change the word from delete to update
> [rocketmq-console] Refine the message when create or update consumer monitor

- rocketmq-flume/pom.xml
- rocketmq-flume/rocketmq-flume-source/src/main/java/org/apache/rocketmq/flume/ng/source/RocketMQSource.java
- rocketmq-flume/rocketmq-flume-source/src/test/java/org/apache/rocketmq/flume/ng/source/RocketMQSourceTest.java
DefaultMQPullConsumer is deprecated after RMQ Version 4.6.0. A better implementation DefaultLitePullConsumer is recommend to use in the scenario of actively pulling messages. We can use it.
Replace the DefaultMQPullConsumer with the DefaultLitePullConsumer
Yes
> [ISSUE #573] (rocketmq-flume)Replace the DefaultMQPullConsumer with the DefaultLitePullConsumer

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
FIX [ISSUE 337](https://github.com/apache/rocketmq-externals/issues/337)
Rethrow exception when sending message to broker fail.
> [ISSUE #337] throw exception when send message to broker fail

- rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/UserServiceImpl.java
issue #658 
Fix login throw NPE when set rocketmq.config.enableDashBoardCollect=false
XXXX
> [ISSUE #658] Login throw NPE when set rocketmq.config.enableDashBoardCollect=false

- rocketmq-iot-bridge/pom.xml
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/MQTTBridge.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/config/MqttBridgeConfig.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/configuration/MQTTBridgeConfiguration.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/common/util/MqttUtil.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/constant/MsgPropertyKeyConstant.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/MessageDispatcher.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/MqttConnectionHandler.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttPublishMessageHandler.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttSubscribeMessageHandler.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/impl/MqttUnsubscribeMessagHandler.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/ConsumerPullTask.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/PublishProducer.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/RocketMQPublishProducer.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/RocketMQSubscribeConsumer.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/rocketmq/SubscribeConsumer.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/subscription/SubscriptionStore.java
- rocketmq-iot-bridge/src/main/java/org/apache/rocketmq/iot/storage/subscription/impl/InMemorySubscriptionStore.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/integration/ConsumeMessageIntegrationTest.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/integration/PubSubIntegrationTest.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/protocol/mqtt/handler/MqttConnectionHandlerTest.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/MqttSubscribeMessageHandlerTest.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/protocol/mqtt/handler/downstream/MqttUnsubscribeMessageHandlerTest.java
- rocketmq-iot-bridge/src/test/java/org/apache/rocketmq/iot/storage/subscription/InMemorySubscriptionTest.java
issue #669 
1. refactor config, add some rmq config
2. add rmq producer for message publish
3. add rmq consumer for message subscribe and unsubscribe
XXXX
> [ISSUE #669] Support RocketMQ as storage of mqtt broker

- rocketmq-console/src/main/java/org/apache/rocketmq/console/config/RMQConfigure.java
- rocketmq-console/src/main/java/org/apache/rocketmq/console/model/request/SendTopicMessageRequest.java
- rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImpl.java
- rocketmq-console/src/main/java/org/apache/rocketmq/console/service/impl/TopicServiceImpl.java
- rocketmq-console/src/main/resources/static/src/i18n/en.js
- rocketmq-console/src/main/resources/static/src/i18n/zh.js
- rocketmq-console/src/main/resources/static/src/topic.js
- rocketmq-console/src/main/resources/static/view/pages/topic.html
- rocketmq-console/src/test/java/org/apache/rocketmq/console/controller/MessageTraceControllerTest.java
- rocketmq-console/src/test/java/org/apache/rocketmq/console/service/impl/MessageTraceServiceImplTest.java
- rocketmq-console/src/test/java/org/apache/rocketmq/console/service/impl/TopicServiceImplTest.java
Send test message with message trace
User can choose send test message with message trace or not.
> [Issue #770] [RocketMQ Console] Send message with message trace

- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java
- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerState.java
- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
- rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java
- rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/rest/RestHandlerTest.java
#695 
Solve the problem of repeated data sending caused by the worker shutdown process.
1. Add worker status
2. Change taskExecutor shutdownNow to awaitTermination
3. Adjust the service shutdown sequence.
XXXX
> [ISSUE #695] Optimized the worker shutdown process.

- rocketmq-flink/pom.xml
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RocketMQConfig.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RocketMQSink.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RocketMQSourceFunction.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RunningChecker.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/selector/DefaultTopicSelector.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/selector/SimpleTopicSelector.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/selector/TopicSelector.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/serialization/KeyValueDeserializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/serialization/KeyValueSerializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/serialization/RowKeyValueDeserializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/serialization/SimpleKeyValueDeserializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/serialization/SimpleKeyValueSerializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/util/MetricUtils.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/util/RetryUtil.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/util/RocketMQUtils.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/common/util/TestUtils.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/example/RocketMQFlinkExample.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/common/RocketMQOptions.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/deserializer/RowDeserializationSchema.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/table/RocketMQDynamicTableSourceFactory.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/table/RocketMQScanTableSource.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/RocketMQSinkTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/RocketMQSourceTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/common/selector/DefaultTopicSelectorTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/common/selector/SimpleTopicSelectorTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/common/serialization/RowKeyValueDeserializationSchemaTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/legacy/common/serialization/SimpleKeyValueSerializationSchemaTest.java
- rocketmq-flink/src/test/java/org/apache/rocketmq/flink/source/table/RocketMQDynamicTableSourceFactoryTest.java
At present, RocketMQ connector supports the implementation of legacy SourceFunction interface, which needs the `ScanTableSource` implementation to expand Table/SQL capabilities. RocketMQ connector should support the RocketMQ TableSource based on the legacy SourceFunction interface.
- Support `RocketMQScanTableSource` based on the implementation `RocketMQSourceFunction` of legacy `SourceFunction` interface.
> [#715] Support the RocketMQ TableSource based on the legacy Source implementation

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/legacy/RocketMQSourceFunction.java
`RocketMQSourceFunction` should support the close of `ExecutorService` and `ScheduledExecutorService` which should be closed when the `SourceOperator` closes.
- Add the close of `ExecutorService` and `ScheduledExecutorService` in the`RocketMQSourceFunction#close`.
> [#786] RocketMQSourceFunction supports the close of ExecutorService and ScheduledExecutorService

- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/reader/RocketMQPartitionSplitReader.java
- rocketmq-flink/src/main/java/org/apache/rocketmq/flink/source/split/RocketMQPartitionSplit.java
`RocketMQPartitionSplitReader` pull the messages from the `MessageQueue` blocking, which affects the throughput of the `RocketMQSource`. It should improve the message consume of `RocketMQPartitionSplitReader`.
- Update the `pullBlockIfNotFound` invoker of `RocketMQPartitionSplitReader` to `pull`.
> [#705] RocketMQSource improves the message consume of RocketMQPartitionSplitReader

- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
assign thread name to worker task thread, do not use default pool-xx-thread-xx format.
> [ISSUE #796] add task woker thread name

- rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
fields put after SinkDataEntry built, SinkDataEntry will include fields.
```java
SinkDataEntry sinkDataEntry = dataEntryBuilder.buildSinkDataEntry(message.getQueueOffset()); 
List<Field> fields = schema.getFields();
if (null != fields && !fields.isEmpty()) {
for (Field field : fields) {
dataEntryBuilder.putFiled(field.getName(), datas[field.getIndex()]);
}
}
return sinkDataEntry;
```
> [ISSUE #798] fields will not be built in SinkDataEntry

- rocketmq-ansible/roles/broker/templates/mqbroker.service
When the host is restarting（For example: runing reboot command）, It using /etc/systemd/system.conf instead of os parameter.
> Systemctl parameter optimization

- rocketmq-spark/pom.xml
- rocketmq-spark/spark-streaming-rocketmq.md
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/RocketMQConfig.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/DefaultMessageRetryManager.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/MQPullConsumerProvider.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/MQPullConsumerProviderFactory.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/MessageSet.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/RocketMQReceiver.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/SimpleMQPullConsumerProvider.java
- rocketmq-spark/src/main/java/org/apache/rocketmq/spark/streaming/SimpleMQPullConsumerProviderFactory.java
- rocketmq-spark/src/main/resources/META-INF/services/org.apache.rocketmq.spark.streaming.MQPullConsumerProviderFactory
- rocketmq-spark/src/main/scala/org/apache/rocketmq/spark/CachedMQConsumer.scala
- rocketmq-spark/src/main/scala/org/apache/rocketmq/spark/ConsumerProvider.scala
- rocketmq-spark/src/main/scala/org/apache/rocketmq/spark/ConsumerProviderFactory.scala
- rocketmq-spark/src/main/scala/org/apache/rocketmq/spark/RocketMqUtils.scala
- rocketmq-spark/src/main/scala/org/apache/spark/sql/rocketmq/CachedRocketMQConsumer.scala
- rocketmq-spark/src/main/scala/org/apache/spark/sql/rocketmq/CachedRocketMQProducer.scala
- rocketmq-spark/src/main/scala/org/apache/spark/sql/rocketmq/RocketMQOffsetReader.scala
- rocketmq-spark/src/main/scala/org/apache/spark/sql/rocketmq/RocketMQSqlUtils.scala
- rocketmq-spark/src/main/scala/org/apache/spark/streaming/MQPullInputDStream.scala
- rocketmq-spark/src/main/scala/org/apache/spark/streaming/RocketMqRDD.scala
- rocketmq-spark/src/test/java/org/apache/rocketmq/spark/sql/RocketMQDataSourceTest.java
- rocketmq-spark/src/test/java/org/apache/rocketmq/spark/streaming/RocketMQReceiverTest.java
Here is some improvements about rocketmq-spark
1. Fix Checkstyle issues about the following class: `RocketMQConfig/MessageSet/DefaultMessageRetryManager/RocketMQReceiver`
2. Bump rocketmq client version from 4.2.0 to 4.9.4
3. Support custom pull consumer using SPI method with interface `MQPullConsumerProviderFactory/MQPullConsumerProvider`
4. Fix the issue about spark streaming job was still running when consumer client failed during start-up process
5. Improving documentation about direct stream and receiver stream
> Some improvements about rocketmq-spark

- rocketmq-rocksdb/README.md
- rocketmq-rocksdb/pom.xml
Polish the rocketmq-rocksdb pom and readme
Polish the rocketmq-rocksdb pom and readme
XXXX
> Polish the rocketmq-rocksdb pom and readme
